### ISSUE TITLE
点击小说 idea很卡

### ISSUE THREAD

**Issue by hyhwl** [nancheung97/legado-reader#3]
连接上后 点击小说很卡 
![image](https://user-images.githubusercontent.com/15354279/216492136-7a5864a7-37b6-4693-8451-8d219e9b51c9.png)
加载不出来章节

**Comment by nancheung97** [comment]
需要配置阅读服务的ip和端口，看图上没有配置呀

**Comment by hyhwl** [comment]
配置了 这个图是点章节进去后出不来 我才知道 不是点章节名  要点面的作者名才能显示出来。 现在的自适应  和字体大小能调节吗 还有背景

**Comment by nancheung97** [comment]
> 配置了 这个图是点章节进去后出不来 我才知道 不是点章节名 要点面的作者名才能显示出来。 现在的自适应 和字体大小能调节吗 还有背景

应该是点击书架目录上任何一个位置都可以跳过去的，对于阅读时的自定义设置(字体大小\颜色等)正在计划中了，自适应是指哪些地方？

**Comment by nancheung97** [comment]
> 配置了 这个图是点章节进去后出不来 我才知道 不是点章节名 要点面的作者名才能显示出来。 现在的自适应 和字体大小能调节吗 还有背景

字体大小调节 #10
